# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv", comment="#", dtype="str")

# Generate useful variables
SAMPLES = samples["sample_id"].drop_duplicates().values.tolist()
SAMPLE_LIB = samples[["sample_id", "library_id"]].values.tolist()
SAMPLE_LIB_PE = samples[samples["library_type"] == "PE"][
    ["sample_id", "library_id"]
].values.tolist()
SAMPLE_LIB_SE = samples[samples["library_type"] == "SE"][
    ["sample_id", "library_id"]
].values.tolist()
HOST_NAMES = (
    [] if features["references"] is None else list(features["references"].keys())
)
MAG_CATALOGUES = list(features["mag_catalogues"].keys())
KRAKEN2_DBS = list(features["databases"]["kraken2"].keys())
BAM_REPORTS = ["stats.tsv", "flagstats.txt", "idxstats.tsv"]
LAST_HOST = HOST_NAMES[-1] if len(HOST_NAMES) > 0 else None


# Import subworkflows
include: "rules/folders.smk"
include: "rules/helpers/_main.smk"
include: "rules/reference/_main.smk"
include: "rules/reads/_main.smk"
include: "rules/preprocess/_main.smk"
include: "rules/stats/_main.smk"
include: "rules/report/_main.smk"


rule all:
    input:
        # rules.reads.input,
        # rules.reference.input,
        # rules.pre.input,
        rules.stats.input,
        rules.report.input,
