# This profile assumes that the study contains 96 samples across an entire
# flowcell
---
__use_yte__: true


default-resources:
    runtime: 1h
    mem_mb: 1024


set-threads:
    reference__recompress__host__: 8
    reference__recompress__mags__: 8
    preprocess__fastp__: 16
    preprocess__fastp__import: 24
    preprocess__kraken2__assign__: 24
    preprocess__index__: 24
    preprocess__bowtie2__cram_to_fastq__: 4
    preprocess__bowtie2__collate_cram__: 24
    preprocess__bowtie2__: 24
    quantify__index__: 24
    quantify__bowtie2__cram_to_fastq__: 4
    quantify__bowtie2__: 24


set-resources:
    preprocess__fastp__:
        mem_mb: 8 * 1024
        runtime: 30m
    preprocess__index__:
        mem_mb: 16 * 1024 * 2 ** (attempt - 1)
        runtime: 4h
    preprocess__bowtie2__cram_to_fastq__:
        mem_mb: 4 * 1024
        runtime: 30m
    preprocess__bowtie2__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 1h
    preprocess__kraken2__assign__:
        mem_mb: 500G
        runtime: 6h
    preprocess__nonpareil__:
        runtime: 24 * 60  # check
    preprocess__singlem__pipe:
        runtime: 24 * 60  # check
        mem_mb: 16G
    preprocess__singlem__condense:
        runtime: 6h  # check
    quantify__index__:
        mem_mb: 16 * 1024 * 2 ** (attempt - 1)
        runtime: 6h
    quantify__bowtie2__cram_to_fastq__:
        mem_mb: 4 * 1024
        runtime: 30m
    quantify__bowtie2__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 4h
    quantify__coverm__genome__aggregate:
        mem_mb: 8G
    quantify__coverm__contig__aggregate:
        mem_mb: 8G
    helpers__samtools__flagstats_cram__:
        mem_mb: 8G
    helpers__samtools__idxstats_cram__:
        mem_mb: 4G
    report__step__reads:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
    report__step__preprocess:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
    report__step__quantify:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
    report__library__:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
