# Default resources for snakemake
---
__use_yte__: true


default-resources:
    - threads=1
    - runtime=60
    - mem_mb=1024


set-threads:
    preprocess__fastp__: 24
    preprocess__fastp__import: 24
    reference__recompress__host__: 8
    reference__recompress__mags__: 8
    preprocess__index__: 24
    quantify__index__: 24
    quantify__bowtie2__: 24


set-resources:
    preprocess__fastp__:
        mem_mb: 8096
        runtime: 30
    preprocess__index__:
        mem_mb: 16 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    preprocess__bowtie2__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    preprocess__kraken2__:
        mem_mb: 500 * 1024
        runtime: 24 * 60
    preprocess__nonpareil__:
        runtime: 24 * 60
    preprocess__singlem__pipe:
        runtime: 24 * 60
        mem_mb: 16 * 1024
    preprocess__singlem__condense:
        runtime: 6 * 60
    quantify__index__:
        mem_mb: 16 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    quantify__bowtie2__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    quantify__coverm__genome__aggregate:
        mem_mb: 8 * 1024
    quantify__coverm__contig__aggregate:
        mem_mb: 8 * 1024
    helpers__samtools_flagstats_cram:
        mem_mb: 8 * 1024
    helpers__samtools_idxstats_cram:
        mem_mb: 4 * 1024
    report__step__reads:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
    report__step__preprocess:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
    report__step__quantify:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
    report__library__:
        mem_mb: 2 * 1024 * 2 ** (attempt - 1)
