# Configuration file for the features, aka, references
---
references:
  human: resources/reference/human_22_sub.fa.gz
  chicken: resources/reference/chicken_39_sub.fa.gz

mag_catalogues:
  mag1: resources/reference/mags_sub.fa.gz
  mag2: resources/reference/mags_sub.fa.gz

databases:
  kraken2:
    mock1: resources/databases/kraken2/kraken2_RefSeqV205_Complete_500GB
    # mock2: resources/kraken2_mock  # another db
  singlem: resoures/databases/singlem/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb
