# Configuration file for the features, aka, references
---
reference:
  human: resources/reference/human_22_sub.fa.gz
  chicken: resources/reference/chicken_39_sub.fa.gz
  mags: resources/reference/mags_sub.fa.gz

kraken2_db: resources/kraken2_mock
