# Configuration file for the features, aka, references and databases
---

hosts:  # Reads will be mapped sequentially
  human: resources/reference/human_22_sub.fa.gz
  chicken: resources/reference/chicken_39_sub.fa.gz
  # GRCh38: resources/references/REF0001-GRC38/GCF_000001405.40_GRCh38.p14_genomic.fna.gz
  # GRCg7b: resources/references/REF0003-GRCg7b/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna.gz
  # Sscrofa11.1: resources/references/REF0002-Sscrofa11.1/GCF_000003025.6_Sscrofa11.1_genomic.fna.gz

mag_catalogues:
  mag1: resources/reference/mags_sub.fa.gz
  # mag2: resources/reference/mags_sub.fa.gz
  # chicken_big_mag: resources/references/mags/chicken_big_mag.fa.gz

databases:
  checkm2: resources/databases/checkm2/20210323/
  checkv: resources/databases/checkv/20230320/checkv-db-v1.5/
  dram: resources/databases/dram/20230811
  genomad: resources/databases/genomad/genomad_db_v1.7
  gtdbtk: resources/databases/gtdbtk/release214
  kraken2:  # add entries as necessary
    refseq500: resources/databases/kraken2/kraken2_RefSeqV205_Complete_500GB/20220505/
  singlem: resources/databases/singlem/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb/
  virsorter2: resources/databases/virsorter2/20200511/


magscot:
  pfam_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_Pfam-A.hmm.gz
  tigr_hmm: workflow/scripts/MAGScoT/hmm/gtdbtk_rel207_tigrfam.hmm.gz
