references:
  human_genome: /projects/mjolnir1/people/jpl786/detection_limit_test_data/resources/reference/GCF_000001405.40_GRCh38.p14_genomic.fna.gz
  chicken_genome: /projects/mjolnir1/people/jpl786/detection_limit_test_data/resources/reference/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna.gz
  metagenome: /projects/mjolnir1/people/jpl786/detection_limit_test_data/resources/reference/mag_catalogue.fna.gz
