# Execution parameters
---

pre:
  fastp:
    length_required: 75  # nonpareil requires at least 25bp
    extra: "--trim_poly_g --trim_poly_x"
  bowtie2:
    extra: ""
    samtools:
      mem_per_thread: 1G

stats:

  kraken2:
    memory_gb: 1
    extra: ""

  coverm:
    genome:
      methods: ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods
      min_covered_fraction: 0.0
      separator: "^"
    contig:
      methods: ["count", "covered_bases", "length"]  # https://github.com/wwood/CoverM#calculation-methods

  singlem:
    threads: 1  # raise it at your own . on the tests one is enough
