# Execution parameters
---

fastp:
  extra: " --length_required 75 --trim_poly_g --trim_poly_x"

bowtie2:
  bowtie2_extra: ""
  samtools_extra: "-m 1G"


quantify:
  bowtie2:
    samtools_mem: 1G
  coverm:   # https://github.com/wwood/CoverM#calculation-methods
    genome:
      methods: ["count", "covered_bases", "length"]
      min_covered_fraction: 0.0
      separator: "@"
    contig:
      methods: ["count", "covered_bases", "length"]
