# Execution parameters
---

preprocess:
  fastp:
    length_required: 75  # nonpareil requires at least 25bp
  bowtie2:  # mem_gb >= mem_host + threads * samtools_mem
    mem_gb: 32
    samtools_mem: 1G
  kraken2:
    memory_gb: 1

quantify:
  bowtie2:  # mem_gb >= mem_mag + threads * samtools_mem
    mem_gb: 64
    samtools_mem: 1G
  coverm:   # https://github.com/wwood/CoverM#calculation-methods
    genome:
      methods: ["count", "covered_bases", "length"]
      min_covered_fraction: 0.0
      separator: "@"
    contig:
      methods: ["count", "covered_bases", "length"]
