# Run tests over snakefile workflow
---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

env:
  CACHE_NUMBER: 0  # Increment this number to invalidate the cache

jobs:

  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Set up caches
        uses: actions/cache@v3
        with:
          path: |
            .snakemake/conda
            ~/.cache/pre-commit/
          key: snakemake-conda-${{ env.CACHE_NUMBER }}

      - name: Clean conda cache
        run: conda clean --all --yes

      - name: Test workflow - Preprocessing
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5
            preprocess

      - name: Test workflow - Stats
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5
            stats

      - name: Test workflow - Report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 5
            report
